---

- set_fact:
    corrected_name: "{{ project['name'] | replace(' ', '-') | lower }}"

- set_fact:
    project:
      path: "{{ path }}/{{ corrected_name }}/"
      owner: "{{ project['owner'] | default(project['author']['name']) }}"

- name: establish project directory skeleton
  file:
    path: "{{ project['path'] }}/{{ item }}"
    state: directory
  with_items:
    - ""
    - "{{ corrected_name }}"
    - "bin"
    - "tests"
  
- name: establish project files
  template:
    src: "{{ item.src }}"
    dest: "{{ project['path'] }}/{{ item.dest }}"
  with_items:
    - { src: setup.py, dest: setup.py  }
    - { src: empty.py, dest: "{{ corrected_name }}/__init__.py" }
    - { src: README.md, dest: README.md }

- name: add project license
  import_role:
    name: dev/create/license
  vars:
    license: "{{ project['license'] }}"
  when: 
    - project['license'] is defined 

- name: add ignore file
  import_role:
    name: dev/create/ignore_file
  vars:
    path: "{{ project['path'] }}"
    language: Python
    ignore: ["bin/"]
  when:
    - scm is defined
   
