---

- name: load prerequisite tasks
  # include_tasks: "{{ lookup('first_found', params, errors='ignore') }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/platform/'
      skip: true

- include_tasks: clang_version.yml
  loop: "{{ versions }}"
  loop_control:
    loop_var: version
