---

- name: load variables
  include_vars: packages.yml

- name: establish package
  become: true
  package:
    name: "{{ basic_packages }}"
    state: present

- name: establish clang tools
  when: clang_install_tools | bool
  become: true
  package:
    name: "{{ advanced_packages }}"
    state: present

- name: update alternatives
  become: true
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/{{ item }}-{{ version }}
    priority: "{{ 50 + (version | int) }}"
    link: /usr/bin/{{ item }}
  loop:
    - clang
    - clang-format
    - clang-tidy
