---

- name: load prerequisite tasks
  loop: "{{ query('first_found', params, errors='ignore') }}"
  include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/platform/'
      skip: true

- include_tasks: clang.yml
  loop: "{{ clang_versions }}"
  loop_control:
    loop_var: version
