---

- name: load prerequisite tasks
  loop: "{{ query('first_found', params, errors='ignore') }}"
  include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/platform/'
      skip: true

- name: load variables
  include_vars: packages.yml

- name: establish package
  become: true
  package:
    name: "{{ basic_packages }}"
    state: present

- name: establish clang tools
  when: clang_install_tools | bool
  become: true
  package:
    name: "{{ advanced_packages }}"
    state: present

- name: update alternatives
  become: true
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/{{ item }}-{{ clang_version }}
    priority: "{{ 50 + (clang_version | int) }}"
    link: /usr/bin/{{ item }}
  loop:
    - clang
    - clang-format
    - clang-tidy
    - clangd
    - lld
