---

- name:
  set_fact:
    project_path: "{{ project['path'] }}/{{ project['name'] | replace(' ', substitutes[' ']) | lower }}/"

- name: ensure project skeleton presence
  file:
    path: "{{ project_path }}/{{ item.dest }}"
    state: directory
  when: item.when is not defined or item.when
  with_items:
    - { dest: "" }
    - { dest: "bin" }
    - { dest: "build" }
    - { dest: "cmake", when: "{{ 'cmake' in uses }}" }
    - { dest: "doc" }
    - { dest: "include" }
    - { dest: "lib" }
    - { dest: "src" }
    - { dest: "test", when: "{{ 'test' in uses }}" }

- name: add license
  block:
  - name: establish license dependency
    pip:
      name: lice
      state: present

  - name: create project license
    shell: lice {{ project['license'] | replace('-','') | lower }} -p "{{ project['name'] }}" {% if 'owner' in project %}-o "{{ project['owner'] }}"{% endif %} > LICENSE.md
    args:
      chdir: "{{ project_path }}"

- name: add project readme
  template:
    src: "README"
    dest: "{{ project_path }}/README.md"

- name: add ignore file
  import_role:
    name: tasks/dev/ignore_files
  vars:
    path: "{{ project_path }}"
    language: "C++"
    ignore: ["bin/", "build/", "lib/"]
  when:
    - scm is defined
