---

- set_fact:
    project:
      owner: "{{ project['owner'] | default(project['author']['name']) }}"
      path: "{{ path }}/{{ project['name'] | replace(' ', substitutes[' ']) | lower }}/"

- name: establish project skeleton presence
  file:
    path: "{{ project['path'] }}/{{ item.dest }}"
    state: directory
  when: item.when is not defined or item.when
  with_items:
    - { dest: "" }
    - { dest: "bin" }
    - { dest: "build" }
    - { dest: "cmake", when: "{{ 'cmake' in uses }}" }
    - { dest: "doc" }
    - { dest: "include" }
    - { dest: "lib" }
    - { dest: "src" }
    - { dest: "test", when: "{{ 'test' in uses }}" }

- name: add project readme
  template:
    src: "README.md"
    dest: "{{ project['path'] }}/README.md"

- name: add project license
  import_role:
    name: dev/create/license
  vars:
    license: "{{ project['license'] }}"
  when:
    - project['license'] is defined

- name: add ignore file
  import_role:
    name: dev/create/ignore_file
  vars:
    path: "{{ project['path'] }}"
    language: "C++"
    ignore:
      - "bin/"
      - "build/"
      - "lib/"
  when:
    - scm is defined
