---

- name: establish integration test directory
  file:
    path: "{{ project['path'] }}/test"
    state: directory
  when: test.integration is defined

- block:
    - name: establish unittest frameworks
      git:
        repo: "{{ frameworks[item]['repo'] }}"
        dest: "{{ project['path'] }}/include/{{ item }}"
        update: no 
      when:
        - item in frameworks
        - "'repo' in frameworks[item]"
      with_items: "{{ test['unittest'] | default([]) }}"
  when: build != 'cmake'

- block:
    - name: ensure external dependency physical absence
      file:
        path: "{{ project['path'] }}/include/{{ item }}"
        state: absent
      when:
        - item in frameworks
        - "'repo' in frameworks[item]"
      with_items: "{{ test['unittest'] | default([]) }}"

    - name: establish external dependencies in CMake
      debug:
        msg: "ESTABLISHING..."
  when: build == 'cmake'
