---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update package manager
      when: "ansible_pkg_mgr == 'apt'"
      apt:
        update_cache: true
  roles:
    - role: ansible-role-clang
      vars:
        clang_versions:
          - 7
          - 8
          - 10
          - 11
          - 12
        clang_install_tools: true
