---

- name: establish apt_key dependency
  become: true
  apt:
    name: gpg-agent
    state: present

- name: ensure repo key presence
  become: true
  apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key
    state: present

- name: ensure repo presence
  become: true
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release | lower }}/ llvm-toolchain-{{ ansible_distribution_release | lower }}-{{ repo_item }} main"    # noqa 204
    state: present
    filename: clang{{ repo_item }}-stable
  loop: "{{ clang_versions }}"
  loop_control:
    loop_var: repo_item

- name: ensure src repo presence
  become: true
  apt_repository:
    repo: "deb-src http://apt.llvm.org/{{ ansible_distribution_release | lower }}/ llvm-toolchain-{{ ansible_distribution_release | lower }}-{{ src_repo_item }} main"    # noqa 204
    state: present
    filename: clang{{ src_repo_item }}-stable
  loop: "{{ clang_versions }}"
  loop_control:
    loop_var: src_repo_item
