---

- name: establish apt_key dependency
  become: true
  apt:
    name: gpg-agent
    state: present

- name: ensure repo key presence
  become: true
  apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key
    state: present

- name: ensure repo presence
  become: true
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release | lower }}/ llvm-toolchain-{{ ansible_distribution_release | lower }}-{{ clang_version }} main"    # noqa 204
    state: present
    filename: clang{{ clang_version }}-stable

- name: ensure src repo presence
  become: true
  apt_repository:
    repo: "deb-src http://apt.llvm.org/{{ ansible_distribution_release | lower }}/ llvm-toolchain-{{ ansible_distribution_release | lower }}-{{ clang_version }} main"    # noqa 204
    state: present
    filename: clang{{ clang_version }}-stable
