---

- name: prepare facts
  set_fact:
    header: "## Project specific"
    ignore_file: "{{ path }}/.{{ scm_to_short[scm] }}ignore" 

- name: establish ignore file
  get_url:
    url: "https://raw.githubusercontent.com/github/gitignore/master/{{ language }}.gitignore"
    dest: "{{ ignore_file }}"

- name: ensure custom header presence
  lineinfile:
    line: "{{ header }}"
    path: "{{ ignore_file }}"
    state: present
  check_mode: yes
  register: _custom_header

- name: establish project label
  shell: echo -e "\n## Project specific" >> {{ ignore_file }}
  args:
    executable: bash
  when: _custom_header is changed

- name: ensure git exclusion for directories
  lineinfile:
    line: "{{ item }}"
    path: "{{ ignore_file }}"
    state: present
  with_items: "{{ ignore }}"
